def _apply_thrust(self, creature, old_angles, dt):
    
    """
    Calculate and apply thrust generated by the angular motion of segments.
    Returns the total thrust force and a list of thrust vectors for visualization.
    """
    
    thrust = np.zeros(2)
    thrust_vectors = []
    
    seg_len = creature.segment_length
    num_seg = creature.num_segments

    for i in range(num_seg):
        
        # Calculate angular velocity (change in angle)
        delta_angle = creature.segment_angles[i] - old_angles[i]
        
        # If the angle didn't change, no thrust is generated
        if abs(delta_angle) < 1e-8:
            thrust_vectors.append([0.0, 0.0])
            continue

        # The swept area of fluid = (1/2) × L^2 × angular_variation
        # This multiplied by a thrust coeff provides the magnitude of the thrust due to this angle variation
        swept_area = 0.5 * seg_len**2 * abs(delta_angle)
        magnitude = self.thrust_coefficient * swept_area

        # Determine thrust direction
        # This angle is the CCW orientation of the segment w.r.t. the x axis
        seg_world_angle = creature.base_orientation + creature.segment_angles[i]
        
        # Thrust acts perpendicular to the segment.
        # The sign of the angle change determines left/right perpendicular direction.
        # copysign is cleaner than if/else for determining direction
        # +pi/2 for CCW rotation (positive delta), -pi/2 for CW rotation (negative delta)
        direction_offset = math.copysign(math.pi / 2, delta_angle)
        thrust_angle = seg_world_angle + direction_offset
        
        thrust_dir = np.array([math.cos(thrust_angle), math.sin(thrust_angle)])
        segment_thrust = magnitude * thrust_dir
        
        # We sum the thrust of each angular change
        thrust += segment_thrust
        
        # Add the current thrust to the thrust vectors
        thrust_vectors.append(segment_thrust.tolist())

    # 5. Apply physics update
    creature.head_vel += thrust * dt
    
    return thrust, thrust_vectors