import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import random
import math
import copy
import pickle
import os
from datetime import datetime

# ==========================================================
#       PHYSICS MODEL CLASS
# ==========================================================

def parse_physics_model(filepath):
    """Function to parse physics model parameters from a configuration file."""

    DEFAULT = {"thrust_coefficient": 3.5, "angle_speed": 0.4, "drag_spread_factor": 2.0}
    
    config = {}
    
    try:
        with open(filepath, 'r') as f:
            for line in f:
                line = line.strip()
                
                if "thrust_coefficient" in line and "=" in line:   config["thrust_coefficient"] = float(line.split("=")[1].strip())
                elif "angle_speed" in line and "=" in line:        config["angle_speed"]        = float(line.split("=")[1].strip())
                elif "drag_spread_factor" in line and "=" in line: config["drag_spread_factor"] = float(line.split("=")[1].strip())
                
            return config
        
    except FileNotFoundError:
        print("Configuration file 'PhysicsModel.txt' not found. Using default parameters.")
        return DEFAULT

class PhysicsModel:

    """
    Aquatic propulsion physics model.
    Handles thrust generation from segment rotation and drag calculation.
    """

    def __init__(self, thrust_coefficient=10.0, 
                 angle_speed=0.4, drag_spread_factor=1.2):
        
        self.angle_speed        = angle_speed
        self.thrust_coefficient = thrust_coefficient
        self.drag_spread_factor = drag_spread_factor

    def apply_drag(self, creature, dt):
    
        """
        Calculate and apply drag based on segment orientations relative to velocity.
        Returns the total drag force and a list of drag vectors for visualization.
        """
        
        # Retrieve creature properties
        speed   = np.linalg.norm(creature.head_vel)
        num_seg = creature.num_segments
        seg_len = creature.segment_length
        
        # If the creature is stationary, no drag is generated
        if speed == 0: return np.zeros_like(creature.head_vel), []

        # This angle is the one of the velocity vector w.r.t. the x axis
        vel_angle = math.atan2(creature.head_vel[1], creature.head_vel[0])
        
        # We compute the sum of the perpendicular projections of all segments
        total_projected_area = 0.0
        drag_vectors = []
        for i in range(num_seg):
            
            # This angle is the CCW orientation of the segment w.r.t. the x axis
            seg_world_angle = creature.base_orientation + creature.segment_angles[i]
            
            # We compute the section perpendicular to the velocity vector
            angle_to_velocity = seg_world_angle - vel_angle
            projected_width = abs(math.sin(angle_to_velocity))
            segment_area = projected_width * seg_len
            
            # The tail segments are less affected by the drag
            total_projected_area += segment_area * ((num_seg - i) / num_seg)

            # Add the current drag to the drag vectors
            # Note: We use 'projected_width' here to get a coefficient normalized by length
            vis_coeff = self.drag_spread_factor * projected_width * ((num_seg - i) / num_seg)
            vis_force = -vis_coeff * creature.head_vel * speed
            drag_vectors.append(vis_force.tolist())

        # Calculate total drag force
        # Normalize area by length to get a coefficient independent of segment resolution
        effective_width = total_projected_area / seg_len
        drag_coeff = self.drag_spread_factor * effective_width
        
        # Drag force: -Coeff * Speed * Velocity_Vector
        drag_force = -drag_coeff * creature.head_vel * speed

        # Apply the drag to slow down the progression of the creature
        creature.head_vel += drag_force * dt

        return drag_force, drag_vectors

    def apply_thrust(self, creature, old_angles, dt):
    
        """
        Calculate and apply thrust generated by the angular motion of segments.
        Returns the total thrust force and a list of thrust vectors for visualization.
        """
        
        thrust = np.zeros(2)
        thrust_vectors = []
        
        seg_len = creature.segment_length
        num_seg = creature.num_segments

        for i in range(num_seg):
            
            # Calculate angular velocity (change in angle)
            delta_angle = creature.segment_angles[i] - old_angles[i]
            
            # If the angle didn't change, no thrust is generated
            if abs(delta_angle) < 1e-8:
                thrust_vectors.append([0.0, 0.0])
                continue

            # The swept area of fluid = (1/2) × L^2 × angular_variation
            # This multiplied by a thrust coeff provides the magnitude of the thrust due to this angle variation
            swept_area = 0.5 * seg_len**2 * abs(delta_angle)
            magnitude = self.thrust_coefficient * swept_area

            # Determine thrust direction
            # This angle is the CCW orientation of the segment w.r.t. the x axis
            seg_world_angle = creature.base_orientation + creature.segment_angles[i]
            
            # Thrust acts perpendicular to the segment.
            # The sign of the angle change determines left/right perpendicular direction.
            # copysign is cleaner than if/else for determining direction
            # +pi/2 for CCW rotation (positive delta), -pi/2 for CW rotation (negative delta)
            direction_offset = math.copysign(math.pi / 2, delta_angle)
            thrust_angle = seg_world_angle + direction_offset
            
            # Compute the thrust relative to this segment
            thrust_dir = np.array([math.cos(thrust_angle), math.sin(thrust_angle)])
            segment_thrust = magnitude * thrust_dir
            
            # We sum the thrust of each angular change
            thrust += segment_thrust
            
            # Add the current thrust to the thrust vectors
            thrust_vectors.append(segment_thrust.tolist())

        # We apply the thrust to modify the progression of the creature
        creature.head_vel += thrust * dt
        
        return thrust, thrust_vectors

    def update_physics(self, creature, dt):
        """Update creature's position and velocity based on physics.
           Return the thrust and drag vectors for visualization"""

        # Store old angles for thrust calculation
        old_angles = creature.segment_angles.copy()
        
        # Update angles towards target
        for i in range(creature.num_segments):
            diff = creature.target_angles[i] - creature.segment_angles[i]
            creature.segment_angles[i] += diff * self.angle_speed
        
        # Apply thrust from angle changes (modifies the head velocity vector)
        thrust, thrust_vectors = self.apply_thrust(creature, old_angles, dt)
        
        # Apply drag (modifies the norm of the head velocity vector)
        drag_force, drag_vectors = self.apply_drag(creature, dt)
        
        # Update position of the head
        creature.head_pos = creature.head_pos + creature.head_vel * dt
        
        return thrust, thrust_vectors, drag_force, drag_vectors

# ==========================================================
#       CREATURE CLASS
# ==========================================================

def parse_creature(filepath):

    DEFAULT = {"segment_length": 3.0, "size_penalty_factor": 0.25,
               "fixed_segments": True, "num_segments": 2,
               "min_segments": 2, "max_segments": 10,
               "target_angle_deg": 0, "max_angle_deg": 180.0,
               "use_nn": False,
               "base_energy": 100.0, "metabolism_rate": 0.002,
               "energy_cost_angle_move": 0.03,
               "energy_cost_add_segment": 3.0, "energy_cost_remove_segment": 1.5,
               "angle_step": 10}
    
    config = {}
    
    try:
        with open(filepath, 'r') as f:
            for line in f:
                line = line.strip()
                
                if   "segment_length" in line and "=" in line:              config["segment_length"]             = float(line.split("=")[1].strip())
                elif "size_penalty_factor" in line and "=" in line:         config["size_penalty_factor"]        = float(line.split("=")[1].strip())
                elif "fixed_segments" in line and "=" in line:              config["fixed_segments"]             = True if "true" in line.split("=")[1].strip().lower() else False
                elif "num_segments" in line and "=" in line:                config["num_segments"]               = int(line.split("=")[1].strip())
                elif "min_segments" in line and "=" in line:                config["min_segments"]               = int(line.split("=")[1].strip())
                elif "max_segments" in line and "=" in line:                config["max_segments"]               = int(line.split("=")[1].strip())
                elif "target_angle_deg" in line and "=" in line:            config["target_angle_deg"]           = float(line.split("=")[1].strip())
                elif "max_angle_deg" in line and "=" in line:               config["max_angle_deg"]              = float(line.split("=")[1].strip())
                elif "use_nn" in line and "=" in line:                      config["use_nn"]                     = True if "true" in line.split("=")[1].strip().lower() else False
                elif "base_energy" in line and "=" in line:                 config["base_energy"]                = float(line.split("=")[1].strip())
                elif "metabolism_rate" in line and "=" in line:             config["metabolism_rate"]            = float(line.split("=")[1].strip())
                elif "energy_cost_angle_move" in line and "=" in line:      config["energy_cost_angle_move"]     = float(line.split("=")[1].strip())
                elif "energy_cost_add_segment" in line and "=" in line:     config["energy_cost_add_segment"]    = float(line.split("=")[1].strip())
                elif "energy_cost_remove_segment" in line and "=" in line:  config["energy_cost_remove_segment"] = float(line.split("=")[1].strip())
                elif "angle_step" in line and "=" in line:                  config["angle_step"]                 = float(line.split("=")[1].strip())
            return config
        
    except FileNotFoundError:
        print("Configuration file 'Creature.txt' not found. Using default parameters.")
        return DEFAULT

class Creature:

    """
    Aquatic creature with segment-based body.
    The creature has multiple body segments that can rotate independently.
    Energy is consumed for movement and metabolism.
    """

    def __init__(self,
                 segment_length=3.0, size_penalty_factor=0.25,
                 fixed_segments=True, num_segments=2,
                 min_segments=2, max_segments=10,
                 target_angle_deg=0, max_angle_deg=180.0,
                 use_nn=True,
                 base_energy=100.0, metabolism_rate=0.002,
                 energy_cost_angle_move=0.03,
                 energy_cost_add_segment=3.0, energy_cost_remove_segment=1.5,
                 angle_step=10):
        
        # Body configuration
        self.segment_length      = float(segment_length)       # Segment length
        self.size_penalty_factor = float(size_penalty_factor)  # Size factor for energy consumption (bigger creature = more energy consumption)
        
        # Number of segment
        self.fixed_segments = bool(fixed_segments) # Can the creature modify the number of segments?
        self.num_segments   = int(num_segments)    # The current number of segments
        self.min_segments   = int(min_segments)    # The minimal number of segments
        self.max_segments   = int(max_segments)    # The maximal number of segments

        # Initialize the current number of segments to minimum if the number of segments is not fixed
        if not fixed_segments: self.num_segments = int(min_segments)
        
        # Movement configuration
        self.target_angle_deg = float(target_angle_deg)                     # The desired direction of progression in °
        self.base_orientation = math.radians(target_angle_deg)              # The equivalent in radians
        self.direction_vector = np.array([math.cos(self.base_orientation),
                                          math.sin(self.base_orientation)]) # Unitary direction vector for desired movement
        
        # Learning configuration
        self.use_nn = bool(use_nn) # Can the creature learn by using a neural network?
        
        # Energy configuration
        self.base_energy = float(base_energy) # Base level of energy
        self.max_energy  = float(base_energy) # Maximal level of energy (will depend on the size)
        self.energy      = float(base_energy) # Current level of energy

        self.metabolism_rate            = float(metabolism_rate)               # Energy cost to stay alive
        self.energy_cost_angle_move     = float(energy_cost_angle_move)        # Energy cost to rotate a segment
        self.energy_cost_add_segment    = float(energy_cost_add_segment)       # Energy cost to add a segment
        self.energy_cost_remove_segment = float(energy_cost_remove_segment)    # Energy cost to remove a segment
        
        # Segment angles: orientation of each segment relative to base_orientation
        # Arrays are always sized to max_segments to allow for dynamic add/remove
        self.max_angle      = math.radians(float(max_angle_deg))             # The maximal angle of the segment w.r.t. base_orientation
        self.segment_angles = np.zeros(int(max_segments), dtype=np.float64)  # The current values of the angles
        self.target_angles  = np.zeros(int(max_segments), dtype=np.float64)  # The current values of the angles after chosen action

        # Angle delta for a movement
        self.angle_step_deg = angle_step                # Angle delta for a movement in °
        self.angle_step_rad = math.radians(angle_step)  # Equivalent in radians
        
        # Position and velocity
        self.head_pos = np.array([0.0, 0.0], dtype=np.float64)  # Position of the head of the creature
        self.head_vel = np.array([0.0, 0.0], dtype=np.float64)  # Velocity vector of the head
        
        # Starting position tracking
        self.start_pos = np.array([0.0, 0.0], dtype=np.float64)

    def reset_creature(self, x=0.0, y=0.0, orientation=None):
        """Reset the creature for a new episode."""

        # Reset orientation
        self.base_orientation = orientation if orientation is not None else self.base_orientation
        
        # Straight body: all segments aligned with base_orientation
        self.segment_angles[:self.num_segments] = 0.0
        self.target_angles[:self.num_segments]  = 0.0
        
        # Reset position and velocity
        self.head_pos = np.array([x, y], dtype=np.float64)
        self.head_vel = np.array([0.0, 0.0], dtype=np.float64)
        
        # Track starting position
        self.start_pos = np.array([x, y], dtype=np.float64)
        
        # Reset energy level
        self.energy = self.max_energy

        # The max energy level depends on the current size of the creature
        self.max_energy = self.base_energy * self.get_body_size_factor()

    def get_body_size_factor(self):
        """Calculate energy multiplier based on body size."""
        return 1.0 + (self.num_segments - 2) * self.size_penalty_factor
    
    def consume_energy_metabolism(self):
        """Consume energy for staying alive."""

        # Compute the energy cost for staying alive
        size_factor = self.get_body_size_factor()
        energy_cost = self.metabolism_rate * size_factor

        # Ensures that the creature still has enough energy to stay alive
        if self.energy - energy_cost < 0:
            self.energy = 0
            return [False]

        # If it's the case, decrease the level of energy
        self.energy -= energy_cost

        return [True, energy_cost]
    
    def consume_energy_angle_move(self, angle_delta):
        """Consume energy for changing segment orientation."""

        # Compute the energy cost to make the move
        size_factor = self.get_body_size_factor()
        energy_cost = self.energy_cost_angle_move * abs(angle_delta) * size_factor
        
        # Ensures that the creature still has enough energy to make the move
        if self.energy - energy_cost < 0:
            return [False]
        
        # If it's the case, decrease the energy level of the creature
        self.energy -= energy_cost

        return [True, energy_cost]
    
    def add_segment(self):
        """Add a new segment to the creature if possible."""

        # Compute the energy cost to add a segment
        size_factor = self.get_body_size_factor()
        energy_cost = self.energy_cost_add_segment * size_factor
        
        # Ensures that we don't exceed the maximal number of segments
        if self.num_segments >= self.max_segments:
            return [False]
        
        # And that the creature still has enough energy to add the segment
        if self.energy - energy_cost < 0:
            return [False]
        
        # If it's the case,
        self.energy       -= energy_cost # Decrease the energy level of the creature
        self.num_segments += 1           # Increase the number of segments

        # Update max energy based on new body size and ensure current energy does not exceed new max
        self.max_energy = self.base_energy * self.get_body_size_factor()
        self.energy     = min(self.energy, self.max_energy)
        
        # Initialize the orientation variables for the new segment
        self.segment_angles[self.num_segments - 1] = 0.0
        self.target_angles[self.num_segments - 1]  = 0.0
        
        return [True, energy_cost]
    
    def remove_segment(self):
        """Remove a segment from the creature if possible."""

        # Compute the energy cost to remove a segment
        size_factor = self.get_body_size_factor()
        energy_cost = self.energy_cost_remove_segment * size_factor
        
        # Ensures that we don't go below the minimal number of segments
        if self.num_segments <= self.min_segments:
            return [False]
        
        # And that the creature still has enough energy to remove the segment
        if self.energy - energy_cost < 0:
            return [False]
        
        # If it's the case,
        self.energy       -= energy_cost # Decrease the energy level of the creature
        self.num_segments -= 1           # Decrease the number of segments

        # Update max energy based on new body size and ensure current energy does not exceed new max
        self.max_energy = self.base_energy * self.get_body_size_factor()
        self.energy     = min(self.energy, self.max_energy)

        # Reset the removed segment's angles to 0 (for cleanliness when re-adding later)
        # Do NOT resize the arrays - they stay at max_segments capacity
        self.segment_angles[self.num_segments] = 0.0
        self.target_angles[self.num_segments]  = 0.0

        return [True, energy_cost]
    
    def get_trajectory_frame(self):
        """Get current state as a dictionary for trajectory recording."""

        return {'pos': self.head_pos.copy(),                                        # The current position of the creature's head in 2D space.
                'segment_angles': self.segment_angles[:self.num_segments].copy(),   # The angles of the segments relative to the base orientation.
                'num_segments': self.num_segments,                                  # The current number of segments the creature has.
                'energy': self.energy,                                              # The current energy level of the creature.
                'base_orientation': self.base_orientation}                          # The base orientation of the creature.

# ==========================================================
#       LEARNING PROCESS CLASS
# ==========================================================

def parse_learning_process(filepath):

    DEFAULT = {"use_nn": False, "learning_rate_nn": 0.001, "learning_rate_tabular": 0.15, "gamma": 0.9,
               "coeff_dist": 0.05, "coeff_vel": 0.5, "coeff_energy": 0.005,
               "epsilon_min": 0.05}
    
    config = {}
    
    try:
        with open(filepath, 'r') as f:
            for line in f:
                line = line.strip()
                
                if   "use_nn" in line and "=" in line:               config["use_nn"]               = True if "true" in line.split("=")[1].strip().lower() else False
                elif "learning_rate_nn" in line and "=" in line:     config["learning_rate_nn"]     = float(line.split("=")[1].strip())
                elif "learning_rate_tabular" in line and "=" in line: config["learning_rate_tabular"] = float(line.split("=")[1].strip())
                elif "gamma" in line and "=" in line:                config["gamma"]                = float(line.split("=")[1].strip())
                elif "coeff_dist" in line and "=" in line:           config["coeff_dist"]           = float(line.split("=")[1].strip())
                elif "coeff_vel" in line and "=" in line:            config["coeff_vel"]            = float(line.split("=")[1].strip())
                elif "coeff_energy" in line and "=" in line:         config["coeff_energy"]         = float(line.split("=")[1].strip())
                elif "epsilon_min" in line and "=" in line:          config["epsilon_min"]          = float(line.split("=")[1].strip())
            return config
        
    except FileNotFoundError:
        print("Configuration file 'LearningProcess.txt' not found. Using default parameters.")
        return DEFAULT

class QTabular:
    """
    Tabular Q-learning with state discretization.
    
    The Q-table is a dictionary:
    - Key: tuple of N segment angles (the state)
    - Value: array of Q-values, one per action (size = 3*N + 2 if variable segments)
    
    For N segments:
    - State dimension: N (one angle per segment)
    - Action dimension: 3*N (+ 2 for add/remove if variable segments)
    """

    def __init__(self, 
                 state_dim, action_dim,
                 learning_rate=0.15):

        # Dimensions
        self.state_dim  = state_dim   # Number of segments (state = N segment angles)
        self.action_dim = action_dim  # Number of actions = 3*N (+ 2 if variable segments)

        self.q_table = {}             # Q-table: {state_tuple: Q-values array}
        self.learning_rate = learning_rate

    def get_q_values(self, state):
        """Retrieve the Q-values array for a given state."""

        # Convert state to tuple (hashable for dictionary key)
        state_key = tuple(np.round(state, 4))  # Round to avoid floating point issues

        # Initialize Q-values to 0 if state not seen before
        if state_key not in self.q_table:
            self.q_table[state_key] = np.zeros(self.action_dim)
        
        return self.q_table[state_key]
    
    def update_q_values(self, state, action, target):
        """
        Update a single Q-value using the Q-learning update rule:
        Q(s,a) = Q(s,a) + learning_rate * (target - Q(s,a))
        """

        state_key = tuple(np.round(state, 4))

        if state_key not in self.q_table:
            self.q_table[state_key] = np.zeros(self.action_dim)

        # Q-learning update
        self.q_table[state_key][action] = self.q_table[state_key][action] + self.learning_rate * (target - self.q_table[state_key][action])
    
    def load_q_table(self, q_table_dict):
        """Load a Q-table from a dictionary (with lists converted to numpy arrays)."""
        self.q_table = {}
        for state_key, q_values in q_table_dict.items():
            # Convert state_key back to tuple if it's a string representation
            if isinstance(state_key, str):
                # Parse string like "(0.0, 0.1, 0.2)" back to tuple
                state_key = tuple(float(x.strip()) for x in state_key.strip('()').split(','))
            self.q_table[state_key] = np.array(q_values)
        print(f"Loaded Q-table with {len(self.q_table)} states")


class EfficientQNetwork(nn.Module):
    """
    Efficient Neural Network for Q-value approximation.
    
    Optimized for fast training and inference:
    - Smaller hidden layers (64 -> 32) for speed
    - Single hidden layer to reduce computation
    - No LayerNorm for faster forward passes
    - Suitable for real-time learning
    
    Architecture: Linear -> ReLU -> Linear -> ReLU -> Linear
    """
    
    def __init__(self, state_dim, action_dim):
        super(EfficientQNetwork, self).__init__()
        
        self.state_dim = state_dim
        self.action_dim = action_dim
        
        # Efficient architecture: fewer layers, smaller dimensions
        self.network = nn.Sequential(
            nn.Linear(state_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, action_dim)
        )
        
        # Initialize weights
        self._init_weights()
    
    def _init_weights(self):
        """Initialize network weights using Xavier initialization."""
        for layer in self.network:
            if isinstance(layer, nn.Linear):
                nn.init.xavier_uniform_(layer.weight)
                nn.init.zeros_(layer.bias)
    
    def forward(self, x):
        """Forward pass through the network."""
        return self.network(x)
    
    def get_q_values(self, state):
        """Get Q-values for all actions given a state."""
        with torch.no_grad():
            state_tensor = torch.from_numpy(state).float() if isinstance(state, np.ndarray) else state.float()
            return self.forward(state_tensor).numpy()
    
    def adapt_dimensions(self, new_state_dim, new_action_dim):
        """
        Adapt the network to new input/output dimensions while preserving hidden weights.
        This method modifies the network in-place.
        """
        if new_state_dim == self.state_dim and new_action_dim == self.action_dim:
            return self
        
        # Get current hidden layer weights
        old_layers = list(self.network.children())
        old_fc1 = old_layers[0]  # First Linear
        old_fc2 = old_layers[2]  # Second Linear
        old_fc3 = old_layers[4]  # Third Linear (output)
        
        # Create new network with adapted dimensions
        new_network = nn.Sequential(
            nn.Linear(new_state_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, new_action_dim)
        )
        
        with torch.no_grad():
            # Copy input layer weights (preserve overlapping inputs)
            new_fc1 = new_network[0]
            min_state = min(self.state_dim, new_state_dim)
            new_fc1.weight[:, :min_state] = old_fc1.weight[:, :min_state]
            new_fc1.bias[:] = old_fc1.bias[:]
            if new_state_dim > self.state_dim:
                # Initialize new input dimensions
                nn.init.xavier_uniform_(new_fc1.weight[:, self.state_dim:])
            
            # Copy hidden layer (unchanged)
            new_network[2].weight[:] = old_fc2.weight[:]
            new_network[2].bias[:] = old_fc2.bias[:]
            
            # Copy output layer weights (preserve overlapping outputs)
            new_fc3 = new_network[4]
            min_action = min(self.action_dim, new_action_dim)
            new_fc3.weight[:min_action, :] = old_fc3.weight[:min_action, :]
            new_fc3.bias[:min_action] = old_fc3.bias[:min_action]
            if new_action_dim > self.action_dim:
                # Initialize new output dimensions
                nn.init.xavier_uniform_(new_fc3.weight[self.action_dim:, :])
                nn.init.zeros_(new_fc3.bias[self.action_dim:])
        
        self.network = new_network
        self.state_dim = new_state_dim
        self.action_dim = new_action_dim
        
        return self


class FlexibleQNetwork(nn.Module):
    """
    Flexible Neural Network that can adapt input/output dimensions while preserving hidden weights.
    
    This network uses a slightly larger architecture than EfficientQNetwork for better
    learning capacity, but still optimized for speed.
    
    Architecture: Linear -> LayerNorm -> ReLU -> Linear -> ReLU -> Linear
    """
    
    def __init__(self, state_dim, action_dim):
        super(FlexibleQNetwork, self).__init__()
        
        self.state_dim = state_dim
        self.action_dim = action_dim
        
        # Balanced architecture: moderate size with LayerNorm for stability
        self.input_layer = nn.Linear(state_dim, 128)
        self.ln1 = nn.LayerNorm(128)
        self.hidden = nn.Linear(128, 64)
        self.output_layer = nn.Linear(64, action_dim)
        
        # Initialize weights
        self._init_weights()
    
    def _init_weights(self):
        """Initialize network weights using Xavier initialization."""
        for layer in [self.input_layer, self.hidden, self.output_layer]:
            nn.init.xavier_uniform_(layer.weight)
            nn.init.zeros_(layer.bias)
    
    def forward(self, x):
        """Forward pass through the network."""
        x = self.input_layer(x)
        x = self.ln1(x)
        x = torch.relu(x)
        x = self.hidden(x)
        x = torch.relu(x)
        x = self.output_layer(x)
        return x
    
    def get_q_values(self, state):
        """Get Q-values for all actions given a state."""
        with torch.no_grad():
            state_tensor = torch.from_numpy(state).float() if isinstance(state, np.ndarray) else state.float()
            return self.forward(state_tensor).numpy()
    
    def adapt_dimensions(self, new_state_dim, new_action_dim):
        """
        Adapt the network to new input/output dimensions while preserving hidden weights.
        """
        if new_state_dim == self.state_dim and new_action_dim == self.action_dim:
            return self
        
        # Create new input layer
        new_input = nn.Linear(new_state_dim, 128)
        with torch.no_grad():
            min_state = min(self.state_dim, new_state_dim)
            new_input.weight[:, :min_state] = self.input_layer.weight[:, :min_state]
            new_input.bias[:] = self.input_layer.bias[:]
            if new_state_dim > self.state_dim:
                nn.init.xavier_uniform_(new_input.weight[:, self.state_dim:])
        
        # Create new output layer
        new_output = nn.Linear(64, new_action_dim)
        with torch.no_grad():
            min_action = min(self.action_dim, new_action_dim)
            new_output.weight[:min_action, :] = self.output_layer.weight[:min_action, :]
            new_output.bias[:min_action] = self.output_layer.bias[:min_action]
            if new_action_dim > self.action_dim:
                nn.init.xavier_uniform_(new_output.weight[self.action_dim:, :])
                nn.init.zeros_(new_output.bias[self.action_dim:])
        
        # Replace layers
        self.input_layer = new_input
        self.output_layer = new_output
        
        # Update dimensions
        self.state_dim = new_state_dim
        self.action_dim = new_action_dim
        
        return self


class LearningProcess:

    """
    Q-learning implementation supporting both neural network and tabular approaches.

    State: segment angles (N values for N segments)
    Actions: open/close/hold for each segment = 3*N actions (+ add/remove if variable = 2 more)
    
    Q-learning update: Q(s,a) = Q(s,a) + learning_rate * (target - Q(s,a))
    where target = cost + gamma * min_a' Q(s', a')
    """

    def __init__(self,
                 state_dim, action_dim,
                 use_nn=False, 
                 learning_rate_nn=0.001, learning_rate_tabular = 0.15,
                 gamma = 0.95,
                 coeff_dist=0.05, coeff_vel=0.5, coeff_energy=0.005,
                 epsilon_min=0.05):
        
        # Dimensions
        self.state_dim  = state_dim   # Number of segments (state = N segment angles)
        self.action_dim = action_dim  # Number of actions = 3*N (+ 2 if variable segments)

        # Whether to use or not a neural network
        self.use_neural_network = use_nn

        # If yes, initializes the Neural Network and use ADAM as optimizer
        if use_nn:
            # Use EfficientQNetwork for faster training
            self.model = EfficientQNetwork(state_dim, action_dim)
            self.optimizer = optim.Adam(self.model.parameters(), lr=learning_rate_nn)

        # Otherwise, initializes the Tabular model
        else:
            self.model     = QTabular(state_dim, action_dim, learning_rate=learning_rate_tabular)
            self.optimizer = None

        # Learning rates
        self.learning_rate_nn      = learning_rate_nn
        self.learning_rate_tabular = learning_rate_tabular

        # Discount factor
        self.gamma = gamma

        # Coefficients for objective function
        self.coeff_dist   = coeff_dist
        self.coeff_vel    = coeff_vel
        self.coeff_energy = coeff_energy

        # Minimum epsilon for epsilon-greedy strategy
        self.epsilon_min = epsilon_min

    def update_dimensions(self, new_state_dim, new_action_dim):
        """Update model dimensions when segment count changes.
        
        IMPORTANT: 
        - For tabular Q-learning, we preserve existing Q-values for states that are still valid.
        - For neural network, we use adapt_dimensions which preserves hidden layer weights.
        """
        
        if new_state_dim == self.state_dim and new_action_dim == self.action_dim:
            return  # No change needed
        
        old_state_dim = self.state_dim
        old_action_dim = self.action_dim
        
        # Update dimensions
        self.state_dim = new_state_dim
        self.action_dim = new_action_dim
        
        if self.use_neural_network:
            # Use adapt_dimensions to preserve hidden weights
            self.model.adapt_dimensions(new_state_dim, new_action_dim)
            # Recreate optimizer with new parameters
            self.optimizer = optim.Adam(self.model.parameters(), lr=self.learning_rate_nn)
        else:
            # For tabular Q-learning, preserve existing Q-values
            old_q_table = self.model.q_table.copy()
            self.model = QTabular(new_state_dim, new_action_dim, learning_rate=self.learning_rate_tabular)
            
            # Copy over Q-values for states that are still valid
            for state_key, q_values in old_q_table.items():
                # Handle state dimension change
                if new_state_dim > old_state_dim:
                    # Segment added - pad state with 0
                    new_state_key = state_key + (0.0,) * (new_state_dim - old_state_dim)
                elif new_state_dim < old_state_dim:
                    # Segment removed - truncate state
                    new_state_key = state_key[:new_state_dim]
                else:
                    new_state_key = state_key
                
                # Copy Q-values for overlapping actions
                new_q = np.zeros(new_action_dim)
                min_actions = min(old_action_dim, new_action_dim)
                new_q[:min_actions] = q_values[:min_actions]
                
                self.model.q_table[new_state_key] = new_q

    def update_q_values(self, state, action, cost, next_state):
        """Update Q-values based on experience.

           The formula is: Q(S,A) = Q(S,A) + learning_rate * [ (C + gamma * min_A' Q(S',A') ) - Q(S,A) ]
           where:
                - S/A are the current state/action
                - S' is the next state the agent moves to
                - A' is the best next action in state S'
                - gamma is the discount factor
                - C is the cost received for taking action A in state S
        """

        # If we use a neural network...
        if self.use_neural_network:
            with torch.no_grad():
                q_next = self.model.get_q_values(next_state)                      # Retrieve Q-values for next state
                target = cost + self.gamma * np.min(q_next)                       # Compute target = C + gamma * min_A' Q(S',A')
            
            # Compute loss and update weights
            state_tensor = torch.from_numpy(state).float()
            q_values = self.model.forward(state_tensor)
            current_q = q_values[action]
            target_tensor = torch.tensor(target, dtype=torch.float32)
            loss = nn.MSELoss()(current_q, target_tensor)
            
            self.optimizer.zero_grad()
            loss.backward()
            nn.utils.clip_grad_norm_(self.model.parameters(), 1.0)
            self.optimizer.step()

        # Otherwise...
        else:
            q_next = self.model.get_q_values(next_state)                          # Retrieve Q-values for next state
            target = cost + self.gamma * np.min(q_next)                           # Compute target = C + gamma * min_A' Q(S',A')
            self.model.update_q_values(state, action, target)                     # Update Q-table

    def calculate_reward(self, creature, energy_cost):
        """Calculate reward based on creature state."""

        # Retrieve the current distance wandered from the start along the desired direction,
        # Based on the current head position
        distance = np.dot(creature.head_pos - creature.start_pos, creature.direction_vector)

        # Retrieve the future distance wandered in addition along the desired direction,
        # Based on the current head velocity
        speed     = np.linalg.norm(creature.head_vel)
        alignment = np.dot(creature.head_vel / (speed+1e-8), creature.direction_vector)

        # Store those information
        info = {'distance': distance,'speed': speed,'alignment': alignment}
        
        # Calculate reward components
        reward_speed    = alignment * speed * self.coeff_vel
        reward_distance = distance * self.coeff_dist
        penalty_energy  = energy_cost * self.coeff_energy
        reward          = reward_speed + reward_distance - penalty_energy
        
        return reward, info
    
    def select_action(self, state, epsilon):
        """Select action using epsilon-greedy strategy."""

        # Generate a random value between 0 and 1,
        # if it's less than epsilon, we explore (random action)
        if random.random() < epsilon:
            return random.randint(0, self.action_dim - 1)
        
        # Otherwise,
        # we exploit the learned values by choosing the action with the lowest Q-value for the current state
        else:

            # If we use a neural network...
            if self.use_neural_network:
                with torch.no_grad():
                    q_values = self.model.get_q_values(state)
                    return int(np.argmin(q_values))
            
            # Otherwise...
            else:
                q_values = self.model.get_q_values(state)
                return int(np.argmin(q_values))
            
    def get_epsilon(self, episode, total_episodes):
        """Calculate current epsilon with linear decay."""
        return max(self.epsilon_min, 1.0 - (episode / total_episodes) * (1.0 - self.epsilon_min))
    
    def get_model_state(self):
        """Get current model state for checkpointing."""
        if self.use_neural_network:
            return self.model.state_dict()
        else:
            # Convert numpy arrays to lists for serialization
            return {k: v.tolist() for k, v in self.model.q_table.items()}
    
    def load_pretrained_model(self, model_path):
        """
        Load a pre-trained model from a .pth file (neural network) or .pkl file (tabular).
        
        Args:
            model_path: Path to the model file (.pth for NN, .pkl for tabular)
        
        Returns:
            True if successful, False otherwise
        """
        if not os.path.exists(model_path):
            print(f"Model file not found: {model_path}")
            return False
        
        try:
            if self.use_neural_network:
                # Load neural network weights
                state_dict = torch.load(model_path, map_location='cpu')
                self.model.load_state_dict(state_dict)
                print(f"Loaded neural network weights from: {model_path}")
                print(f"  State dim: {self.model.state_dim}, Action dim: {self.model.action_dim}")
            else:
                # Load tabular Q-table
                with open(model_path, 'rb') as f:
                    data = pickle.load(f)
                
                if isinstance(data, dict):
                    # Check if it's a Q-table or a full export
                    if 'q_table' in data:
                        self.model.load_q_table(data['q_table'])
                    else:
                        # Assume it's the Q-table directly
                        self.model.load_q_table(data)
                print(f"Loaded Q-table from: {model_path}")
                print(f"  States loaded: {len(self.model.q_table)}")
            
            return True
            
        except Exception as e:
            print(f"Error loading model: {e}")
            return False


def load_model_from_export(export_txt_path, learning_process):
    """
    Load a model from an exported .txt file.
    
    This function parses the export file and loads the model weights.
    For neural networks, it looks for the accompanying .pth file.
    For tabular, it parses the Q-table entries from the text.
    
    Args:
        export_txt_path: Path to the export .txt file
        learning_process: The LearningProcess instance to load into
    
    Returns:
        True if successful, False otherwise
    """
    if not os.path.exists(export_txt_path):
        print(f"Export file not found: {export_txt_path}")
        return False
    
    # For neural networks, look for the corresponding .pth file
    if learning_process.use_neural_network:
        # The .pth file has the same timestamp as the .txt file
        dir_path = os.path.dirname(export_txt_path)
        base_name = os.path.basename(export_txt_path)
        
        # Extract timestamp from filename like "training_export_20241201_120000.txt"
        if 'training_export_' in base_name:
            timestamp = base_name.replace('training_export_', '').replace('.txt', '')
            pth_path = os.path.join(dir_path, f'model_weights_{timestamp}.pth')
            
            if os.path.exists(pth_path):
                return learning_process.load_pretrained_model(pth_path)
            else:
                print(f"Neural network weights file not found: {pth_path}")
                return False
        else:
            print("Could not determine .pth file path from export filename")
            return False
    else:
        # For tabular, parse the Q-table from the text file
        try:
            q_table = {}
            with open(export_txt_path, 'r') as f:
                content = f.read()
            
            # Find the Q-TABLE ENTRIES section
            if 'Q-TABLE ENTRIES' in content:
                lines = content.split('\n')
                in_q_table = False
                current_state = None
                
                for line in lines:
                    if 'Q-TABLE ENTRIES' in line:
                        in_q_table = True
                        continue
                    
                    if in_q_table:
                        if line.startswith('State ('):
                            # Parse state: "State (0.0000, 0.1000, -0.2000):"
                            state_str = line.split('State ')[1].split(':')[0].strip()
                            current_state = tuple(float(x.strip()) for x in state_str.strip('()').split(','))
                        elif line.strip().startswith('Q-values:'):
                            # Parse Q-values: "Q-values: [0.1234, -0.5678, ...]"
                            q_values_str = line.split('Q-values:')[1].strip()
                            q_values = [float(x.strip()) for x in q_values_str.strip('[]').split(',')]
                            if current_state is not None:
                                q_table[current_state] = np.array(q_values)
                        elif 'END OF EXPORT' in line:
                            break
                
                if q_table:
                    learning_process.model.load_q_table(q_table)
                    print(f"Loaded Q-table from export file: {export_txt_path}")
                    return True
                else:
                    print("No Q-table entries found in export file")
                    return False
            else:
                print("Export file does not contain Q-table section")
                return False
                
        except Exception as e:
            print(f"Error parsing export file: {e}")
            return False


# ==========================================================
#       TRAINING CHECKPOINT CLASS
# ==========================================================

class TrainingCheckpoint:
    """Checkpoint container for saving training state."""
    
    def __init__(self, episode, model_state, trajectory, max_distance, use_nn, num_segments):

        self.episode      = episode                     # Current episode number
        self.model_state  = model_state                 # State of the learning model (Q-table or neural network weights)
        self.trajectory   = trajectory                  # Trajectory of the creature for this episode
        self.max_distance = max_distance                # Max distance reached in this episode
        self.use_nn       = use_nn                      # Whether the model is a neural network or tabular model
        self.num_segments = num_segments                # Current number of segments of the creature

# ==========================================================
#       SIMULATION CLASS
# ==========================================================

def parse_simulation(filepath):
        
    DEFAULT = {"min_segments" : 2, "max_segments" : 10,
               "duration_simulation" : 30.0, "dt" : 0.01, "substeps" : 5,
               "episodes" : 300, "checkpoint_interval" : 20}
    
    config = {}
    
    try:
        with open(filepath, 'r') as f:
            for line in f:
                line = line.strip()
                
                if   "min_segments" in line and "=" in line:        config["min_segments"]        = int(line.split("=")[1].strip())
                elif "max_segments" in line and "=" in line:        config["max_segments"]        = int(line.split("=")[1].strip())
                elif "duration_simulation" in line and "=" in line: config["duration_simulation"] = float(line.split("=")[1].strip())
                elif "dt" in line and "=" in line:                  config["dt"]                  = float(line.split("=")[1].strip())
                elif "substeps" in line and "=" in line:            config["substeps"]            = int(line.split("=")[1].strip())
                elif "episodes" in line and "=" in line:            config["episodes"]            = int(line.split("=")[1].strip())
                elif "checkpoint_interval" in line and "=" in line: config["checkpoint_interval"] = int(line.split("=")[1].strip())

            return config

    except FileNotFoundError:
        print(f"Configuration file '{filepath}' not found. Using default parameters.")
        return DEFAULT

class Simulation:
    """Main simulation class that orchestrates creature, physics, and learning."""
    
    def __init__(self,
                 min_segments=2, max_segments=10,
                 duration_simulation=30.0, dt=0.01, substeps=5,
                 episodes=300, checkpoint_interval=20):
        
        # Min/Max segments for variable number
        self.min_segments = int(min_segments)
        self.max_segments = int(max_segments)

        # Episode parameters
        self.episodes            = episodes              # Number of episodes
        self.checkpoint_interval = checkpoint_interval   # Save every checkpoint_interval for the visualization tool

        # Duration parameter
        self.dt                  = float(dt)                      # Time step for each update in sec
        self.duration_simulation = float(duration_simulation)     # Duration of the simulation in sec
        self.max_steps           = int(duration_simulation // dt) # Total number of update
        self.substeps            = int(substeps)                  # Substeps for physics update
        
        # Store script directory for saving results
        self.script_dir = os.path.dirname(os.path.abspath(__file__))
        
        # Initialize the creature             
        config = parse_creature(os.path.join(self.script_dir, "Creature.txt"))
        self.creature = Creature(**config)
        
        # Ensures that the Min/Max numbers of segments of the creature are coherent with the environnement
        self.creature.min_segments = max(self.min_segments, self.creature.min_segments)
        self.creature.max_segments = min(self.max_segments, self.creature.max_segments)

        # Initialize the physics model
        config = parse_physics_model(os.path.join(self.script_dir, "PhysicsModel.txt")) 
        self.physics_model = PhysicsModel(**config)
        
        # The state and action dimensions of the Learning Process depend on the number of segments of the creature
        # The state dimension is the number of segments (orientation of each segment)
        # The action dimension is 3 times the number of segments (open/close/hold each segment) + 2 (add/remove a segment) if variable segments
        state_dim = self.creature.num_segments
        action_dim = 3 * self.creature.num_segments + (0 if self.creature.fixed_segments else 2)

        # Initialize the learning process (ONLY ONCE - do not reset between episodes!)
        config = parse_learning_process(os.path.join(self.script_dir, "LearningProcess.txt")) 
        self.learning_process = LearningProcess(state_dim=state_dim, action_dim=action_dim,
                                                use_nn=self.creature.use_nn, **config)
        
        # Training state
        self.step_count      = 0             # Current number of steps done in the episode
        self.trajectory      = []            # Current trajectory
        self.checkpoints     = []            # Checkpoints to save for the visualization tool
        self.best_distance   = -float('inf') # Best distance found so far
        self.best_trajectory = []            # Best corresponding trajectory

    def reset_simu(self):
        """Reset simulation for a new episode.
        
        IMPORTANT: Do NOT reset the learning process here!
        The Q-table/NN must persist across episodes for learning to accumulate.
        """

        # Reinitialize the number of steps done
        self.step_count = 0

        # Reset the creature state
        self.creature.reset_creature(0.0, 0.0, self.creature.base_orientation)
        
        # Reset num_segments to minimum if variable
        if not self.creature.fixed_segments:
            self.creature.num_segments = self.creature.min_segments
        
        # Update learning process dimensions if needed (preserves Q-values/hidden weights!)
        state_dim = self.creature.num_segments
        action_dim = 3 * self.creature.num_segments + (0 if self.creature.fixed_segments else 2)
        self.learning_process.update_dimensions(state_dim, action_dim)
        
        # Clear trajectory
        self.trajectory = []
        
        # Return initial state = segment angles (only active segments)
        return self.creature.segment_angles[:self.creature.num_segments].copy()

    def _apply_action(self, action, prev_num_segments):
        """Apply action and return result [success, energy_cost or segment_changed, ...]."""
        
        # Handle add/remove segment actions for variable segments
        if not self.creature.fixed_segments:
            
            # ADD segment action (second to last action)
            if action == self.learning_process.action_dim - 2:
                
                result_add = self.creature.add_segment()  # Try to add a segment
                
                # If it worked...
                if result_add[0] == True:
                    segment_changed = ("ADD", self.creature.num_segments)                                                       # Updates the information relative to the change
                    energy_cost = result_add[1]                                                                                # Retrieve the energy cost relative to this add
                    self.learning_process.update_dimensions(self.creature.num_segments, (3 * self.creature.num_segments) + 2)  # Update the dimension of the learning process
                    return [True, segment_changed, energy_cost, True]                                                           # Return with dimensions_changed=True
                
                # Otherwise, don't modify anything
                return [False]
            
            # REMOVE segment action (last action)
            elif action == self.learning_process.action_dim - 1:
                
                result_remove = self.creature.remove_segment()  # Try to remove a segment
                
                # If it worked...
                if result_remove[0] == True:
                    segment_changed = ("REMOVE", self.creature.num_segments)                                                  # Updates the information relative to the change
                    energy_cost = result_remove[1]                                                                            # Retrieve the energy cost relative to this remove
                    self.learning_process.update_dimensions(self.creature.num_segments, (3 * self.creature.num_segments) + 2) # Update the dimension of the learning process
                    return [True, segment_changed, energy_cost, True]                                                          # Return with dimensions_changed=True
                
                # Otherwise, don't modify anything
                return [False]
            
        #====================================================================================================
        
        # Segment rotation actions
        segment_idx = action // 3
        action_type = action % 3

        # If the chosen action is to rotate counter-clockwise (open)...
        if action_type == 0:

            delta_angle = self.creature.angle_step_rad # Retrieve the angle variation of the creature

            # The creature tries to move a segment based on its current level of energy
            result_move = self.creature.consume_energy_angle_move(delta_angle)

            # If it worked...
            if result_move[0] == True:

                new_angle = self.creature.target_angles[segment_idx] + delta_angle                      # Add this variation to the target angles (angles updated in physics)
                new_angle_clip = np.clip(new_angle, -self.creature.max_angle, self.creature.max_angle)  # Clip this value to -180, 180 (For example, an angle of 170° + 20° becomes 10°)
                self.creature.target_angles[segment_idx] = new_angle_clip                               # Update the target angles

                # return the energy cost of this move
                return [True, result_move[1]]

            # Otherwise, don't modify anything
            return [False]
        
        #====================================================================================================
        
        # If the chosen action is to rotate clockwise (close)...
        elif action_type == 1:

            delta_angle = self.creature.angle_step_rad # Retrieve the angle variation of the creature

            # The creature tries to move a segment based on its current level of energy
            result_move = self.creature.consume_energy_angle_move(delta_angle)

            # If it worked...
            if result_move[0] == True:

                new_angle = self.creature.target_angles[segment_idx] - delta_angle                      # Subtract this variation from the target angles (angles updated in physics)
                new_angle_clip = np.clip(new_angle, -self.creature.max_angle, self.creature.max_angle)  # Clip this value to -180, 180
                self.creature.target_angles[segment_idx] = new_angle_clip                               # Update the target angles

                # return the energy cost of this move
                return [True, result_move[1]]

            # Otherwise, don't modify anything
            return [False]
        
        #====================================================================================================
        
        # If the chosen action is to hold the current angle...
        return [True, 0.0]

    def step(self, action):
        """Execute one simulation step."""
        
        # Store the current number of segments BEFORE applying the action
        prev_num_segments = self.creature.num_segments
        
        result_metabolism = self.creature.consume_energy_metabolism() # Apply metabolism (may fail based on the energy level)
        result_action = self._apply_action(action, prev_num_segments) # Apply action (may fail based on the energy level)
        
        # Check if dimensions changed (segment count changed)
        dimensions_changed = len(result_action) == 4 and result_action[3] == True
        
        # Physics update with substeps
        # If the action failed, no thrust is generated, only drag
        for _ in range(self.substeps):
            thrust, thrust_vectors, drag_force, drag_vectors = self.physics_model.update_physics(
                self.creature, self.dt / self.substeps)
        
        # Computes the total energy based on whether the action and metabolism failed or not
        if result_metabolism[0] == False:
            total_energy_cost = 0                                           # If the metabolism failed, the action also failed and the total consumed cost is 0
        elif result_action[0] == False:
            total_energy_cost = result_metabolism[1]                        # If the metabolism worked but the action failed, the total consumed cost is just the metabolism
        else:
            if len(result_action) >= 3:                
                total_energy_cost = result_metabolism[1] + result_action[2] # If both worked and the action was add or remove
            else:
                total_energy_cost = result_metabolism[1] + result_action[1] # If both worked and the action was an angular move
        
        # Record current trajectory with thrust and drag vectors
        frame = self.creature.get_trajectory_frame()
        frame['thrust_vectors'] = [v.copy() if isinstance(v, list) else v for v in thrust_vectors]
        frame['drag_vectors'] = [v.copy() if isinstance(v, list) else v for v in drag_vectors]
        frame['thrust'] = thrust.tolist() if hasattr(thrust, 'tolist') else list(thrust)
        frame['drag_force'] = drag_force.tolist() if hasattr(drag_force, 'tolist') else list(drag_force)
        self.trajectory.append(frame)
        
        # Calculate reward (creature passed directly)
        reward, info = self.learning_process.calculate_reward(self.creature, total_energy_cost)

        # Updates the infos
        info['segment_changed'] = result_action[1] if len(result_action) >= 3 else None
        info['energy_cost'] = total_energy_cost
        info['dimensions_changed'] = dimensions_changed
        
        # Ensures that we don't overshoot the maximum number of steps and that the creature still has some energy
        self.step_count += 1
        done = self.step_count >= self.max_steps or self.creature.energy <= 0
        
        # Get next state = segment angles (only active segments)
        next_state = self.creature.segment_angles[:self.creature.num_segments].copy()

        # Return the next state, the cost, the done status, the infos, and whether dimensions changed
        return next_state, float(-reward), done, info, dimensions_changed
    
    def run_training(self):
        """Run the training process."""

        print("=" * 60)
        print("TRAINING AQUATIC CREATURE")
        print("=" * 60)
        
        # Use learning_process.use_neural_network instead of creature.use_nn
        print(f"Using {'NEURAL NETWORK (Efficient)' if self.learning_process.use_neural_network else 'TABULAR'} Q-learning")
        print(f"State dim: {self.learning_process.state_dim} (segment angles)")
        print(f"Initial action dim: {self.learning_process.action_dim}")
        print()
        
        for ep in range(self.episodes + 1):

            # Reset environment and get initial state
            state = self.reset_simu()
            epsilon = self.learning_process.get_epsilon(ep, self.episodes)
            max_distance = 0
            
            # At each step...
            for step in range(self.max_steps):

                # Select an action based on learning process
                action = self.learning_process.select_action(state, epsilon)

                # Process the step with the chosen action
                next_state, cost, done, info, dimensions_changed = self.step(action)

                # Update the max distance if needed
                max_distance = max(max_distance, info['distance'])
                
                # Always update Q-values - the EfficientQNetwork handles dimension changes
                # by preserving hidden layer weights
                self.learning_process.update_q_values(state, action, cost, next_state)
                
                # Update the state and break if the creature has no energy left
                state = next_state
                if done:
                    break
            
            # Track best trajectory
            if max_distance > self.best_distance:
                self.best_distance = max_distance
                self.best_trajectory = copy.deepcopy(self.trajectory)
            
            # Save checkpoint if the interval fits
            if ep % self.checkpoint_interval == 0:
                checkpoint = TrainingCheckpoint(
                    episode=ep,
                    model_state=self.learning_process.get_model_state(),
                    trajectory=copy.deepcopy(self.best_trajectory),
                    max_distance=self.best_distance,
                    use_nn=self.learning_process.use_neural_network,  # Use learning_process flag
                    num_segments=self.creature.num_segments)
                
                self.checkpoints.append(checkpoint)
                
                # Count Q-table entries for tabular learning
                if self.learning_process.use_neural_network:
                    table_info = "NN"
                else:
                    table_info = f"{len(self.learning_process.model.q_table)} states"
                
                print(f"Ep {ep:3d} | Best: {self.best_distance:6.1f}m | "
                      f"Segs: {self.creature.num_segments} | {table_info}")
        
        print("-" * 60)
        print(f"Done! {len(self.checkpoints)} checkpoints saved.")
        
        return self.learning_process.model, self.checkpoints
    
# ==========================================================
#       UTILITY FUNCTIONS
# ==========================================================

def ensure_result_folder(script_dir):
    """Ensure the Result folder exists in the script directory."""
    result_dir = os.path.join(script_dir, "Result")
    if not os.path.exists(result_dir):
        os.makedirs(result_dir)
    return result_dir

def export_results_txt(sim, checkpoints, script_dir):
    """
    Export comprehensive simulation results to a .txt file.
    
    This function exports:
    1. All simulation parameters from configuration files
    2. Training results (best distance, episodes, etc.)
    3. For Neural Network: Full network architecture and all weights/biases
    4. For Tabular: Q-table state-action values
    """
    result_dir = ensure_result_folder(script_dir)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filepath = os.path.join(result_dir, f"training_export_{timestamp}.txt")
    
    with open(filepath, 'w') as f:
        # Header
        f.write("=" * 80 + "\n")
        f.write("AQUATIC CREATURE Q-LEARNING TRAINING EXPORT\n")
        f.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write("=" * 80 + "\n\n")
        
        # ==========================================================
        # CREATURE PARAMETERS
        # ==========================================================
        f.write("-" * 80 + "\n")
        f.write("CREATURE PARAMETERS (from Creature.txt)\n")
        f.write("-" * 80 + "\n")
        creature = sim.creature
        f.write(f"segment_length = {creature.segment_length}\n")
        f.write(f"size_penalty_factor = {creature.size_penalty_factor}\n")
        f.write(f"fixed_segments = {creature.fixed_segments}\n")
        f.write(f"num_segments (initial) = {creature.num_segments}\n")
        f.write(f"min_segments = {creature.min_segments}\n")
        f.write(f"max_segments = {creature.max_segments}\n")
        f.write(f"target_angle_deg = {creature.target_angle_deg}\n")
        f.write(f"max_angle_deg = {math.degrees(creature.max_angle)}\n")
        f.write(f"angle_step = {creature.angle_step_deg}\n")
        f.write(f"base_energy = {creature.base_energy}\n")
        f.write(f"metabolism_rate = {creature.metabolism_rate}\n")
        f.write(f"energy_cost_angle_move = {creature.energy_cost_angle_move}\n")
        f.write(f"energy_cost_add_segment = {creature.energy_cost_add_segment}\n")
        f.write(f"energy_cost_remove_segment = {creature.energy_cost_remove_segment}\n")
        f.write("\n")
        
        # ==========================================================
        # PHYSICS MODEL PARAMETERS
        # ==========================================================
        f.write("-" * 80 + "\n")
        f.write("PHYSICS MODEL PARAMETERS (from PhysicsModel.txt)\n")
        f.write("-" * 80 + "\n")
        physics = sim.physics_model
        f.write(f"thrust_coefficient = {physics.thrust_coefficient}\n")
        f.write(f"angle_speed = {physics.angle_speed}\n")
        f.write(f"drag_spread_factor = {physics.drag_spread_factor}\n")
        f.write("\n")
        
        # ==========================================================
        # LEARNING PROCESS PARAMETERS
        # ==========================================================
        f.write("-" * 80 + "\n")
        f.write("LEARNING PROCESS PARAMETERS (from LearningProcess.txt)\n")
        f.write("-" * 80 + "\n")
        lp = sim.learning_process
        f.write(f"use_neural_network = {lp.use_neural_network}\n")
        f.write(f"learning_rate_nn = {lp.learning_rate_nn}\n")
        f.write(f"learning_rate_tabular = {lp.learning_rate_tabular}\n")
        f.write(f"gamma (discount factor) = {lp.gamma}\n")
        f.write(f"epsilon_min = {lp.epsilon_min}\n")
        f.write(f"coeff_dist = {lp.coeff_dist}\n")
        f.write(f"coeff_vel = {lp.coeff_vel}\n")
        f.write(f"coeff_energy = {lp.coeff_energy}\n")
        f.write(f"state_dim = {lp.state_dim}\n")
        f.write(f"action_dim = {lp.action_dim}\n")
        f.write("\n")
        
        # ==========================================================
        # SIMULATION PARAMETERS
        # ==========================================================
        f.write("-" * 80 + "\n")
        f.write("SIMULATION PARAMETERS (from Simulation.txt)\n")
        f.write("-" * 80 + "\n")
        f.write(f"duration_simulation = {sim.duration_simulation}\n")
        f.write(f"dt = {sim.dt}\n")
        f.write(f"substeps = {sim.substeps}\n")
        f.write(f"episodes = {sim.episodes}\n")
        f.write(f"checkpoint_interval = {sim.checkpoint_interval}\n")
        f.write(f"max_steps = {sim.max_steps}\n")
        f.write("\n")
        
        # ==========================================================
        # TRAINING RESULTS
        # ==========================================================
        f.write("-" * 80 + "\n")
        f.write("TRAINING RESULTS\n")
        f.write("-" * 80 + "\n")
        f.write(f"best_distance = {sim.best_distance}\n")
        f.write(f"total_checkpoints = {len(checkpoints)}\n")
        f.write(f"final_num_segments = {sim.creature.num_segments}\n")
        f.write("\n")
        
        # ==========================================================
        # NEURAL NETWORK ARCHITECTURE AND WEIGHTS
        # ==========================================================
        if lp.use_neural_network:
            model = lp.model
            f.write("=" * 80 + "\n")
            f.write("NEURAL NETWORK ARCHITECTURE AND FULL EXPORT\n")
            f.write("=" * 80 + "\n")
            
            # Determine network type
            if isinstance(model, EfficientQNetwork):
                f.write("Network Type: EfficientQNetwork (fast, adaptive)\n")
            elif isinstance(model, FlexibleQNetwork):
                f.write("Network Type: FlexibleQNetwork (dimension-adaptive)\n")
            else:
                f.write(f"Network Type: {type(model).__name__} (custom)\n")
            
            f.write(f"Input Dimension (state_dim): {model.state_dim}\n")
            f.write(f"Output Dimension (action_dim): {model.action_dim}\n")
            f.write("\n")
            
            # Architecture description
            f.write("-" * 40 + "\n")
            f.write("ARCHITECTURE LAYERS:\n")
            f.write("-" * 40 + "\n")
            
            if isinstance(model, EfficientQNetwork):
                f.write(f"  Architecture: Linear({model.state_dim} -> 64) -> ReLU -> Linear(64 -> 32) -> ReLU -> Linear(32 -> {model.action_dim})\n")
            elif isinstance(model, FlexibleQNetwork):
                f.write(f"  input_layer: Linear({model.state_dim} -> 128)\n")
                f.write(f"  ln1: LayerNorm(128)\n")
                f.write(f"  activation: ReLU\n")
                f.write(f"  hidden: Linear(128 -> 64)\n")
                f.write(f"  activation: ReLU\n")
                f.write(f"  output_layer: Linear(64 -> {model.action_dim})\n")
            else:
                # Generic network
                f.write("  Network Structure:\n")
                for name, param in model.named_parameters():
                    f.write(f"    {name}: shape={list(param.shape)}\n")
            
            f.write("\n")
            
            # Full weights and biases export
            f.write("=" * 80 + "\n")
            f.write("FULL NETWORK WEIGHTS AND BIASES\n")
            f.write("=" * 80 + "\n")
            
            # Export each parameter
            for name, param in model.named_parameters():
                shape_str = str(list(param.shape))
                f.write(f"Parameter: {name}\n")
                f.write(f"  Shape: {shape_str}\n")
                f.write(f"  Mean: {param.data.mean().item():.6f}\n")
                f.write(f"  Std: {param.data.std().item():.6f}\n")
                f.write(f"  Min: {param.data.min().item():.6f}\n")
                f.write(f"  Max: {param.data.max().item():.6f}\n")
                f.write(f"  Values:\n")
                
                # Export full tensor as numpy array
                np_array = param.data.cpu().numpy()
                if len(np_array.shape) == 1:
                    f.write("    " + np.array2string(np_array, threshold=np.inf, 
                                                     formatter={'float': lambda x: f"{x:.6f}"}) + "\n")
                elif len(np_array.shape) == 2:
                    for i, row in enumerate(np_array):
                        row_str = np.array2string(row, threshold=np.inf, 
                                                   formatter={'float': lambda x: f"{x:.6f}"})
                        f.write(f"    row[{i}]: {row_str}\n")
                else:
                    f.write("    " + np.array2string(np_array, threshold=np.inf,
                                                     formatter={'float': lambda x: f"{x:.6f}"}) + "\n")
                f.write("\n")
            
            # State_dict export info
            f.write("=" * 80 + "\n")
            f.write("STATE_DICT (for torch.load compatibility)\n")
            f.write("=" * 80 + "\n")
            f.write("Use the following to reconstruct the network:\n")
            f.write("```python\n")
            f.write("import torch\n")
            if isinstance(model, EfficientQNetwork):
                f.write(f"from aquatic_evolution_qlearning_V17 import EfficientQNetwork\n")
                f.write(f"model = EfficientQNetwork(state_dim={model.state_dim}, action_dim={model.action_dim})\n")
            elif isinstance(model, FlexibleQNetwork):
                f.write(f"from aquatic_evolution_qlearning_V17 import FlexibleQNetwork\n")
                f.write(f"model = FlexibleQNetwork(state_dim={model.state_dim}, action_dim={model.action_dim})\n")
            f.write("model.load_state_dict(torch.load('model_weights.pth'))\n")
            f.write("```\n\n")
            
            # Save state_dict to separate file
            state_dict_path = os.path.join(result_dir, f"model_weights_{timestamp}.pth")
            torch.save(model.state_dict(), state_dict_path)
            f.write(f"State dict saved to: {state_dict_path}\n")
            
            # Also save Q-table for tabular (if we want to reload later)
            q_table_path = os.path.join(result_dir, f"q_table_{timestamp}.pkl")
            with open(q_table_path, 'wb') as qf:
                pickle.dump(lp.model.state_dict() if lp.use_neural_network else lp.model.q_table, qf)
            f.write(f"Model data saved to: {q_table_path}\n")
            
        else:
            # ==========================================================
            # TABULAR Q-TABLE EXPORT
            # ==========================================================
            f.write("=" * 80 + "\n")
            f.write("TABULAR Q-TABLE EXPORT\n")
            f.write("=" * 80 + "\n")
            
            q_table = lp.model.q_table
            f.write(f"Number of visited states: {len(q_table)}\n")
            f.write(f"State dimension: {lp.state_dim}\n")
            f.write(f"Action dimension: {lp.action_dim}\n\n")
            
            f.write("-" * 40 + "\n")
            f.write("Q-TABLE ENTRIES (state -> Q-values)\n")
            f.write("-" * 40 + "\n")
            
            for state_key, q_values in q_table.items():
                state_str = "(" + ", ".join([f"{v:.4f}" for v in state_key]) + ")"
                q_values_str = "[" + ", ".join([f"{v:.4f}" for v in q_values]) + "]"
                best_action = int(np.argmin(q_values))
                f.write(f"State {state_str}:\n")
                f.write(f"  Q-values: {q_values_str}\n")
                f.write(f"  Best action: {best_action} (Q={q_values[best_action]:.4f})\n")
            
            # Save Q-table to pickle file for easy reloading
            q_table_path = os.path.join(result_dir, f"q_table_{timestamp}.pkl")
            with open(q_table_path, 'wb') as qf:
                pickle.dump(q_table, qf)
            f.write(f"\nQ-table saved to: {q_table_path}\n")
        
        f.write("\n")
        f.write("=" * 80 + "\n")
        f.write("END OF EXPORT\n")
        f.write("=" * 80 + "\n")
    
    print(f"Training results exported to: {filepath}")
    return filepath


def save_simulation(checkpoints, use_nn, target_angle, duration, num_segments, fixed_segments, script_dir):
    """Save simulation results to file."""

    result_dir = ensure_result_folder(script_dir)
    timestamp  = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    if use_nn:
        filename = f"simulation_nn_{timestamp}.pkl"
    else:
        filename = f"simulation_tabular_{timestamp}.pkl"
    
    filepath = os.path.join(result_dir, filename)
    
    # Convert checkpoints to serializable format
    serializable_checkpoints = []
    for cp in checkpoints:
        cp_dict = {
            'episode': cp.episode,
            'model_state': cp.model_state,
            'trajectory': cp.trajectory,
            'max_distance': cp.max_distance,
            'use_nn': cp.use_nn,
            'num_segments': cp.num_segments
        }
        serializable_checkpoints.append(cp_dict)
    
    save_data = {
        'checkpoints': serializable_checkpoints,
        'target_angle': target_angle,
        'duration': duration,
        'num_segments': num_segments,
        'fixed_segments': fixed_segments,
        'use_nn': use_nn
    }
    
    try:
        with open(filepath, 'wb') as f:
            pickle.dump(save_data, f, protocol=pickle.HIGHEST_PROTOCOL)
        print(f"Simulation saved to: {filepath}")
        return filepath
    except Exception as e:
        print(f"Error saving simulation: {e}")
        return None


def list_pretrained_models(script_dir):
    """List available pre-trained models in the Result folder."""
    result_dir = os.path.join(script_dir, "Result")
    if not os.path.exists(result_dir):
        return [], []
    
    pth_files = []
    export_files = []
    
    for f in os.listdir(result_dir):
        if f.startswith('model_weights_') and f.endswith('.pth'):
            pth_files.append(os.path.join(result_dir, f))
        elif f.startswith('training_export_') and f.endswith('.txt'):
            export_files.append(os.path.join(result_dir, f))
        elif f.startswith('q_table_') and f.endswith('.pkl'):
            pth_files.append(os.path.join(result_dir, f))  # Q-table pickle files
    
    return sorted(pth_files, reverse=True), sorted(export_files, reverse=True)


# ==========================================================
#       MAIN FUNCTION
# ==========================================================

def main():
    """Main entry point for the simulation."""
    
    print("=" * 60)
    print("   AQUATIC CREATURE TRAINER - V17")
    print("   (Supports loading pre-trained models)")
    print("=" * 60)
    print()

    # Get script directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    
    # Check for pre-trained models
    pth_files, export_files = list_pretrained_models(script_dir)
    
    load_pretrained = False
    model_path = None
    
    if pth_files or export_files:
        print("\nFound pre-trained models:")
        
        if pth_files:
            print("\n  Model weight files (.pth/.pkl):")
            for i, f in enumerate(pth_files[:5]):
                print(f"    {i+1}. {os.path.basename(f)}")
        
        if export_files:
            print("\n  Export files (.txt):")
            offset = len(pth_files[:5])
            for i, f in enumerate(export_files[:5]):
                print(f"    {offset + i + 1}. {os.path.basename(f)}")
        
        print("\n  0. Start fresh training (no pre-trained model)")
        
        try:
            choice = input("\nSelect model to load (or 0 for fresh start): ").strip()
            idx = int(choice)
            
            if idx > 0:
                all_files = (pth_files[:5] if pth_files else []) + (export_files[:5] if export_files else [])
                if idx <= len(all_files):
                    model_path = all_files[idx - 1]
                    load_pretrained = True
                    print(f"\nWill load: {os.path.basename(model_path)}")
        except (ValueError, IndexError):
            print("Invalid selection, starting fresh training.")
    
    # Parse simulation config from script directory
    sim_config = parse_simulation(os.path.join(script_dir, "Simulation.txt"))
    
    # Create simulation
    sim = Simulation(**sim_config)
    
    # Load pre-trained model if selected
    if load_pretrained and model_path:
        if model_path.endswith('.txt'):
            # Load from export file
            load_model_from_export(model_path, sim.learning_process)
        else:
            # Load from .pth or .pkl file
            sim.learning_process.load_pretrained_model(model_path)
    
    # Run training
    model, checkpoints = sim.run_training()
    
    # Save results (pickle format)
    save_simulation(
        checkpoints=checkpoints,
        use_nn=sim.learning_process.use_neural_network,
        target_angle=sim.creature.target_angle_deg,
        duration=sim.duration_simulation,
        num_segments=sim.creature.num_segments,
        fixed_segments=sim.creature.fixed_segments,
        script_dir=script_dir
    )
    
    # Export comprehensive results to .txt file
    export_results_txt(sim, checkpoints, script_dir)

if __name__ == "__main__":
    main()
